"""initial schema

Revision ID: aa520d371334
Revises: 
Create Date: 2026-07-23 15:39:26.665982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa520d371334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_udi_di',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('basic_udi_di', sa.String(length=120), nullable=False),
    sa.Column('issuing_entity_code', sa.Enum('EUDAMED', 'GS1', 'HIBCC', 'ICCBBA', 'IFA', name='issuing_entity_code_enum'), nullable=False),
    sa.Column('manufacturer_srn', sa.String(length=15), nullable=False),
    sa.Column('risk_class', sa.Enum('CLASS_I', 'CLASS_IIA', 'CLASS_IIB', 'CLASS_III', name='risk_class_enum'), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('DEVICE', 'SYSTEM', 'PROCEDURE_PACK', name='device_type_enum'), nullable=False),
    sa.Column('animal_tissues_cells', sa.Boolean(), nullable=False),
    sa.Column('human_tissues_cells', sa.Boolean(), nullable=False),
    sa.Column('human_product_check', sa.Boolean(), nullable=False),
    sa.Column('medicinal_product_check', sa.Boolean(), nullable=False),
    sa.Column('administering_medicine', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('implantable', sa.Boolean(), nullable=False),
    sa.Column('measuring_function', sa.Boolean(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("trim(basic_udi_di) <> ''", name='chk_basic_udi_di_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basic_udi_di')
    )
    op.create_table('validation_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rules_evaluated', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('udi_di', sa.String(length=120), nullable=False),
    sa.Column('issuing_entity_code', sa.Enum('EUDAMED', 'GS1', 'HIBCC', 'ICCBBA', 'IFA', name='issuing_entity_code_enum'), nullable=False),
    sa.Column('basic_udi_di_id', sa.Uuid(), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('device_status', sa.Enum('ON_THE_MARKET', 'NOT_INTENDED_FOR_EU_MARKET', 'NO_LONGER_PLACED_ON_THE_MARKET', name='device_status_enum'), nullable=False),
    sa.Column('sterile', sa.Boolean(), nullable=False),
    sa.Column('sterilization', sa.Boolean(), nullable=False),
    sa.Column('number_of_reuses', sa.Integer(), nullable=False),
    sa.Column('base_quantity', sa.Integer(), nullable=False),
    sa.Column('latex', sa.Boolean(), nullable=False),
    sa.Column('reprocessed', sa.Boolean(), nullable=False),
    sa.Column('intended_purpose', sa.Text(), nullable=True),
    sa.Column('single_use', sa.Boolean(), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('direct_marking_di', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('base_quantity > 0', name='chk_base_quantity_positive'),
    sa.CheckConstraint('number_of_reuses >= -1', name='chk_number_of_reuses'),
    sa.ForeignKeyConstraint(['basic_udi_di_id'], ['basic_udi_di.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('udi_di')
    )
    op.create_table('validation_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_correction', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xml_generation_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('xml_sha256', sa.String(length=64), nullable=True),
    sa.Column('xsd_status', sa.String(length=10), nullable=True),
    sa.Column('xsd_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_emdn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('emdn_code', sa.String(length=50), nullable=False),
    sa.Column('emdn_description', sa.String(length=500), nullable=True),
    sa.Column('emdn_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('first_market_date', sa.Date(), nullable=True),
    sa.Column('withdrawal_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'country_code', name='uq_device_country')
    )
    op.create_table('production_identifier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('identifier_type', sa.Enum('BATCH_NUMBER', 'SERIALISATION_NUMBER', 'MANUFACTURING_DATE', 'EXPIRATION_DATE', 'SOFTWARE_IDENTIFICATION', name='production_identifier_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'identifier_type', name='uq_device_pi_type')
    )
    op.create_table('trade_name',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('trade_name', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_name')
    op.drop_table('production_identifier')
    op.drop_table('market_country')
    op.drop_table('device_emdn')
    op.drop_table('xml_generation_job')
    op.drop_table('validation_result')
    op.drop_table('device')
    op.drop_table('validation_run')
    op.drop_table('basic_udi_di')
    # ### end Alembic commands ###
